apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bwa-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: bwaapp
    spec:
      containers:
      - name: bwaapp
        image: sushantpande/bwaefs:efs 
        imagePullPolicy: Always
        securityContext:
            capabilities:
                add: ["SYS_ADMIN"]
        command: [ "/bin/bash", "-c"]
        #args: ["mkdir /mnt/efs && mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=300,retrans=1,noresvport 172.31.42.102:/ /mnt/efs && while true; do sleep 30; done;"]
        args: ["mkdir /mnt/efs && mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=300,retrans=1,noresvport 172.31.42.102:/ /mnt/efs && python3 /mnt/efs/bwa.py"]


        #args: ["mkdir /mnt/efs && sleep 30000"]
      imagePullSecrets:
      - name: regcred
