apiVersion: batch/v1
kind: Job
metadata:
  name: bwa-deployment-job
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: bwaapp
    spec:
      containers:
      - args:
        - mkdir -p /mnt/efs && mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=300,retrans=1,noresvport
          172.31.42.102:/ /mnt/efs  && python3 /mnt/efs/bwa.py
        command:
        - /bin/bash
        - -c
        env:
        - name: controller
          value: airflow
        image: sushantpande/bwaefs:efs
        imagePullPolicy: Always
        name: bwaapp
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        tty: true
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
