apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
#kind: Pod
metadata:
  name: gatk-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: gatkapp
    spec:
      containers:
      - name: gatkapp
        imagePullPolicy: Always
        resources:
            limits:
                memory: 10Gi
        image: sushantpande/gatk:efs 
        securityContext:
            capabilities:
                add: ["SYS_ADMIN"]
        command: [ "/bin/bash", "-c"]
        #args: ["mkdir /mnt/efs && mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=300,retrans=1,noresvport 172.31.42.102:/ /mnt/efs && while true; do sleep 30; done;"]

        args: ['mkdir /mnt/efs && mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=300,retrans=1,noresvport 172.31.42.102:/ /mnt/efs && python3 /mnt/efs/gatk.py']

      imagePullSecrets:
      - name: regcred
