apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-deployment-job
spec:
  parallelism: 3
  template:
    metadata:
      labels:
        app: vcfapp
    spec:
      containers:
      - args:
        - mkdir -p /mnt/efs && mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=300,retrans=1,noresvport
          172.31.42.102:/ /mnt/efs && pip install pika && python3 /mnt/efs/vcfjobmqsync.py
        command:
        - /bin/bash
        - -c
        env:
        - name: controller
          value: airflow
        image: sushantpande/vcftools:efs
        imagePullPolicy: Always
        name: gatkapp
        resources:
          limits:
            memory: 10Gi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        tty: true
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
